import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {ThemeModeScript} from "flowbite-react";
import "../styles/globals.css";
import FooterComponent from "@/src/components/footer.component";
import HeaderComponent from "@/src/components/header.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
      <HeaderComponent></HeaderComponent>
      <main className="max-w-screen-xl min-h-screen mx-auto items-center justify-center pt-4 pb-4">
          {children}
      </main>

      <FooterComponent></FooterComponent>
      </body>

    </html>
  );
}
